### ISSUE TITLE
960 dimension

### ISSUE THREAD

**Issue by winlucky15** [Kalafinaian/python-img_gist_feature#1]
Hi! Thanks for your code. That works and helps a lot. May I ask how to extract 960 dimension Gist feature by matlab?

**Comment by Yumeka999** [comment]
sure, wait a minute.
In order to get 960-dim vector, you should these operations.

(1) Change ln_orientation
(2) Use mode="gray"

(1) Change ln_orientation
In utils_gist.py  15line:
def __init__(self, n_resize=128, n_w=5, ln_orientation=[8,  8, 8, 8], n_block_num=4, n_prefilt=4):

dim num: (8+8+8+8)*(4*4) = 32*16 = 512
so you should change ln_orientation=[8,  8, 8, 8] to ln_orientation=[15, 15, 15, 15]
then dim num: (15+15+15+15)*(4*4) = 60*16 = 960

(2) Use mode="gray"
np_gist = gist_helper.get_gist_vec(np_img, mode="gray")

**Comment by Yumeka999** [comment]
CN version:
如何得到960维的特征

(1)修改utils_gist.py 第15行的ln_orientation参数
ln_orientation=[8, 8, 8, 8] 改成 ln_orientation=[15, 15, 15, 15]
改之前维度 (8+8+8+8)(44) = 3216 = 512
改之后维度 (15+15+15+15)(44) = 6016 = 960

(2) 使用灰度模式 np_gist = gist_helper.get_gist_vec(np_img, mode="gray")
